### ISSUE TITLE
Error: Can't find Python executable

### ISSUE THREAD

**Issue by TalArbatov** [caspernikus/CoinStats#1]
while im trying to install node_modules i get this error:
 Error: Can't find Python executable "C:\Users\Tal\AppData\Local\Programs\Python", you can set the PYTHON env variable.

it looks like you have a PYTHON enviroment variable on your local machine and i cant run the program without it

**Comment by caspernikus** [comment]
@TalArbatov do you have python installed ?

**Comment by TalArbatov** [comment]
Oh right, not on my new machine...
It could be a good idea to mention Python in the README or the installation guide inside it
